/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import DAO.ManagerFactory;
import DAO.ProdutosDAO;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.swing.JOptionPane;

/**
 *
 * @author jonatas.ferreiraa
 */
public class JProdutos extends javax.swing.JFrame {

    /**
     * Creates new form JProdutos
     */
    public JProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TNomeProduto = new javax.swing.JTextField();
        TCodigoProduto = new javax.swing.JTextField();
        TPeso = new javax.swing.JTextField();
        TEstoque = new javax.swing.JTextField();
        TFornecedor = new javax.swing.JTextField();
        TDimensao = new javax.swing.JTextField();
        TValor = new javax.swing.JTextField();
        TEstoqueMin = new javax.swing.JTextField();
        TDescricao = new javax.swing.JTextField();
        JInserir = new javax.swing.JButton();
        jRead = new javax.swing.JButton();
        jEditar = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Produtos");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TNomeProduto.setBackground(new java.awt.Color(204, 204, 204));
        TNomeProduto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TNomeProduto.setForeground(new java.awt.Color(0, 0, 0));
        TNomeProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TNomeProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 240, 40));

        TCodigoProduto.setBackground(new java.awt.Color(204, 204, 204));
        TCodigoProduto.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TCodigoProduto.setForeground(new java.awt.Color(0, 0, 0));
        TCodigoProduto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TCodigoProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(TCodigoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 250, 40));

        TPeso.setBackground(new java.awt.Color(204, 204, 204));
        TPeso.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TPeso.setForeground(new java.awt.Color(0, 0, 0));
        TPeso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 50));

        TEstoque.setBackground(new java.awt.Color(204, 204, 204));
        TEstoque.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TEstoque.setForeground(new java.awt.Color(0, 0, 0));
        TEstoque.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 230, 50));

        TFornecedor.setBackground(new java.awt.Color(204, 204, 204));
        TFornecedor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        TFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 230, 40));

        TDimensao.setBackground(new java.awt.Color(204, 204, 204));
        TDimensao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TDimensao.setForeground(new java.awt.Color(0, 0, 0));
        TDimensao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TDimensao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 240, 40));

        TValor.setBackground(new java.awt.Color(204, 204, 204));
        TValor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TValor.setForeground(new java.awt.Color(0, 0, 0));
        TValor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 240, 40));

        TEstoqueMin.setBackground(new java.awt.Color(204, 204, 204));
        TEstoqueMin.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TEstoqueMin.setForeground(new java.awt.Color(0, 0, 0));
        TEstoqueMin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TEstoqueMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 240, 40));

        TDescricao.setBackground(new java.awt.Color(204, 204, 204));
        TDescricao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        TDescricao.setForeground(new java.awt.Color(0, 0, 0));
        TDescricao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(TDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 670, 240, 40));

        JInserir.setBackground(new java.awt.Color(204, 204, 204));
        JInserir.setForeground(new java.awt.Color(0, 0, 0));
        JInserir.setText("Inserir");
        JInserir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        JInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JInserirActionPerformed(evt);
            }
        });
        jPanel1.add(JInserir, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 150, 50));

        jRead.setBackground(new java.awt.Color(204, 204, 204));
        jRead.setForeground(new java.awt.Color(0, 0, 0));
        jRead.setText("Read");
        jRead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReadActionPerformed(evt);
            }
        });
        jPanel1.add(jRead, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 170, 190, 50));

        jEditar.setBackground(new java.awt.Color(204, 204, 204));
        jEditar.setForeground(new java.awt.Color(0, 0, 0));
        jEditar.setText("Editar");
        jEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 140, 50));

        jDelete.setBackground(new java.awt.Color(204, 204, 204));
        jDelete.setForeground(new java.awt.Color(0, 0, 0));
        jDelete.setText("Deletar");
        jDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 150, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 20, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 20, 20));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 20, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 20, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 20, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 20, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 20, 20));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 20, 20));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 20, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Tela_Produto.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JInserirActionPerformed
//              EntityManager entityManager = ManagerFactory.getEntityManager();
//        EntityTransaction transaction = entityManager.getTransaction();
//        try {
//            transaction.begin();
//            entityManager.persist(new Produtos(0, "Jonatas.Ojeda", "123321","","","","","",""));
//            transaction.commit();
//        } catch (Exception ex) {
//            transaction.rollback();
//
//        } finally {
//            if (entityManager.isOpen()) {
//                entityManager.close();
//            }
//
//        }

        new ProdutosDAO().inserir(new Produtos(Integer.parseInt(TCodigoProduto.getText()), TNomeProduto.getText(), TPeso.getText(), TEstoque.getText(), TFornecedor.getText(),
                TDescricao.getText(), TDimensao.getText(), TValor.getText(), TEstoqueMin.getText()));

        if ((TCodigoProduto.getText().isEmpty()) || (TNomeProduto.getText().isEmpty()) || (TPeso.getText().isEmpty()) || (TEstoque.getText().isEmpty())
                || (TFornecedor.getText().isEmpty()) || TDescricao.getText().isEmpty() || TDimensao.getText().isEmpty() || TValor.getText().isEmpty()
                || TEstoqueMin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos Obrigatorios. *");
        } else {
            JOptionPane.showMessageDialog(null, "Usuario adicionado com Sucesso.");
            TCodigoProduto.setText(null);
            TNomeProduto.setText(null);
            TPeso.setText(null);
            TEstoque.setText(null);
            TFornecedor.setText(null);
            TDescricao.setText(null);
            TDimensao.setText(null);
            TValor.setText(null);
            TEstoqueMin.setText(null);

        }

    }//GEN-LAST:event_JInserirActionPerformed

    private void jReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReadActionPerformed
        EntityManager entityManager = ManagerFactory.getEntityManager();
        Produtos produto = entityManager.createNamedQuery("Produtos.findByCodigo", Produtos.class)
                .setParameter("codigo", Integer.parseInt(TCodigoProduto.getText()))
               .getSingleResult();

  EntityTransaction transaction = entityManager.getTransaction();
//      Produtos produto = new ProdutosDAO().selecionarPorCodigo(Integer.parseInt(TCodigoProduto.getText()));
      
         try {
            TNomeProduto.setText(produto.getNomeProduto());
            TDescricao.setText(produto.getDescricao());
            TDimensao.setText(produto.getDimensao());
            TEstoque.setText(produto.getEstoque());
            TEstoqueMin.setText(produto.getEstoqueMinimo());
            TFornecedor.setText(produto.getFornecedor());
            TPeso.setText(produto.getPeso());
            TValor.setText(produto.getValor());
        } catch (Exception ex) {
             System.out.println("ok");
            JOptionPane.showMessageDialog(null, "Usuario Não Cadastrado.");
            TNomeProduto.setText(null);
            TPeso.setText(null);
            TEstoque.setText(null);
            TFornecedor.setText(null);
            TDescricao.setText(null);
            TDimensao.setText(null);
            TValor.setText(null);
            TEstoqueMin.setText(null);
            transaction.rollback();

        } finally {
            if (entityManager.isOpen()) {
                entityManager.close();
            }

        }
        System.out.println(produto);
//        if (produto != null ) {
//            TNomeProduto.setText(produto.getNomeProduto());
//            TDescricao.setText(produto.getDescricao());
//            TDimensao.setText(produto.getDimensao());
//            TEstoque.setText(produto.getEstoque());
//            TEstoqueMin.setText(produto.getEstoqueMinimo());
//            TFornecedor.setText(produto.getFornecedor());
//            TPeso.setText(produto.getPeso());
//            TValor.setText(produto.getValor());
//
//        } else {
//            JOptionPane.showMessageDialog(null, "Usuario Não Cadastrado.");
//            TNomeProduto.setText(null);
//            TPeso.setText(null);
//            TEstoque.setText(null);
//            TFornecedor.setText(null);
//            TDescricao.setText(null);
//            TDimensao.setText(null);
//            TValor.setText(null);
//            TEstoqueMin.setText(null);
//
//        }
    }//GEN-LAST:event_jReadActionPerformed

    private void jEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarActionPerformed
//        EntityManager entityManager = ManagerFactory.getEntityManager();
//        EntityTransaction transaction = entityManager.getTransaction();
//        try {
//            transaction.begin();
//            entityManager.merge(new Produtos(1, "Jonatas.Ojedaaa", "123321","","","","","",""));
//            transaction.commit();
//        } catch (Exception ex) {
//            transaction.rollback();
//
//        } finally {
//            if (entityManager.isOpen()) {
//                entityManager.close();
//            }
//
//        }
        new ProdutosDAO().editar(new Produtos(Integer.parseInt(TCodigoProduto.getText()), TNomeProduto.getText(), TPeso.getText(), TEstoque.getText(), TFornecedor.getText(),
                TDescricao.getText(), TDimensao.getText(), TValor.getText(), TEstoqueMin.getText()));

        if ((TCodigoProduto.getText().isEmpty()) || (TNomeProduto.getText().isEmpty()) || (TPeso.getText().isEmpty()) || (TEstoque.getText().isEmpty())
                || (TFornecedor.getText().isEmpty()) || TDescricao.getText().isEmpty() || TDimensao.getText().isEmpty() || TValor.getText().isEmpty()
                || TEstoqueMin.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha todos os Campos Obrigatorios. *");
        } else {
            JOptionPane.showMessageDialog(null, "Dados do Produto alterado com Sucesso.");
            TCodigoProduto.setText(null);
            TNomeProduto.setText(null);
            TPeso.setText(null);
            TEstoque.setText(null);
            TFornecedor.setText(null);
            TDescricao.setText(null);
            TDimensao.setText(null);
            TValor.setText(null);
            TEstoqueMin.setText(null);

        }

    }//GEN-LAST:event_jEditarActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
//              EntityManager entityManager = ManagerFactory.getEntityManager();
//       Produtos produto =  entityManager.createNamedQuery("Produtos.findByCodigo", Produtos.class)
//                .setParameter("codigo", 1)
//                .getSingleResult();
//
//        EntityTransaction transaction = entityManager.getTransaction();
//        try {
//            transaction.begin();
//            entityManager.remove(produto);
//            transaction.commit();
//        } catch (Exception ex) {
//            transaction.rollback();
//
//        } finally {
//            if (entityManager.isOpen()) {
//                entityManager.close();
//            }
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Remover este Produto?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            new ProdutosDAO().excluir(Integer.parseInt(TCodigoProduto.getText()));
            JOptionPane.showMessageDialog(null, "Usuario Removido Com Sucesso.");
            TCodigoProduto.setText(null);
            TNomeProduto.setText(null);
            TPeso.setText(null);
            TEstoque.setText(null);
            TFornecedor.setText(null);
            TDescricao.setText(null);
            TDimensao.setText(null);
            TValor.setText(null);
            TEstoqueMin.setText(null);
        }

    }//GEN-LAST:event_jDeleteActionPerformed

    private void TCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TCodigoProdutoActionPerformed

    }//GEN-LAST:event_TCodigoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JInserir;
    private javax.swing.JTextField TCodigoProduto;
    private javax.swing.JTextField TDescricao;
    private javax.swing.JTextField TDimensao;
    private javax.swing.JTextField TEstoque;
    private javax.swing.JTextField TEstoqueMin;
    private javax.swing.JTextField TFornecedor;
    private javax.swing.JTextField TNomeProduto;
    private javax.swing.JTextField TPeso;
    private javax.swing.JTextField TValor;
    private javax.swing.JButton jDelete;
    private javax.swing.JButton jEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jRead;
    // End of variables declaration//GEN-END:variables
}
